application: mygraphdb
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:

- url: /graphdb
  static_files: doc/README.html
  upload: doc/README.html

- url: /graphdb/doc/.*
  static_dir: doc


- url: /graphdb/.*
  script: api.application
  secure: always

- url: /auth/.*
  script: auth.application
  secure: always

builtins:
- appstats: on
- deferred: on

