application: graphdb
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /graphdb
  static_files: doc/README.html
  upload: doc/README.html

- url: /graphdb/.*
  script: api.application

- url: /auth/.*
  script: auth.application

builtins:
- appstats: on
- deferred: on

