application: graphdb
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /welcome/.*
  script: welcome.application

- url: /browser/.*
  script: ui.application

- url: /prodcat/.*
  script: prodcat.catalog.application

- url: /graphdb/.*
  script: api.application

builtins:
- appstats: on
- deferred: on

